import Head from "next/head";
import { useState } from "react";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";

import Image from "next/image";
import avatar from "../public/avatar.png";
import Keepaki from "../public/Keepaki.png";
import spotaki from "../public/spotaki.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Thongs Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-200 px-10 dark:bg-gray-500 md:px-20 lg:px-60 dark:text-yellow-50">
        <section className="lg:h-screen">  
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">devedbyaki</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl"
                  onClick={() => {
                    setDarkMode(!darkMode);
                  }}
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-purple-400 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-purple-400 font-medium">
              Thong Hoang
            </h2>
            <h3 className="text-2xl py-2">
              Software Engineering student from Tampere.
            </h3>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 sm:pb-0">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            <div className="mx-auto bg-gradient-to-b from-purple-400 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96 ring ring-primary ring-offset-base-100 ring-offset-2">
              <Image src={avatar} layout="fill" objectFit="cover" alt="My avater"/>
            </div>
          </div>
        </section>

        <section className="lg:h-screen pt-5">
          <h3 className="text-4xl font-burtons pt-5 text-purple-400">About Me</h3>
          <div className="text-lg pt-8 font-mono">
            <p className="py-3">
              Hi there. I am an second year <span>Software Engineering</span>  student from Tampere University of Applied Sciences. Lately I have been
              focusing on Fullstack Developing. My experience spans across
              multiple technologies, frontend with HTML, CSS, Javascript, React,
              Vue and Python, Node, Express for backend. Here you can see some
              of my <a href="#">projects</a>.
            </p>
            <p className="py-3">
              Feel free to snoop around on my social media even though there is
              nothing there haha. For inquiries or a how you doing, contact me,
              I will be happy to hear from you.
            </p>
          </div>
        </section>
        <section className="pt-5">
          <h3 className="text-4xl font-burtons py-5 text-purple-400">My Projects</h3>
          {/* Projects listed by cards */}
          <div className="card lg:card-side bg-base-100 shadow-xl my-5">
              <figure>
                <div className="mx-auto w-80 h-80 relative overflow-hidden md:h-96 md:w-96">
                  <Image src={Keepaki} layout="fill" objectFit="cover" alt="Keepaki"/>
                </div>
              </figure>
              <div className="card-body">
                <h2 className="card-title">Keepaki</h2>
                <p>A clone of Google Keep written by me.</p>
                <ul>Function:
                  <li>Register, login</li>
                  <li>Take notes, delete unused notes</li>
                </ul>
                <div className="card-actions justify-end">
                  <div className="badge badge-primary">Reactjs</div>
                  <div className="badge badge-primary">Nodejs</div>
                </div>
              </div>
          </div>

          <div className="card lg:card-side bg-base-100 shadow-xl my-5">
              <figure>
                <div className="mx-auto w-80 h-80 relative overflow-hidden md:h-96 md:w-96">
                  <Image src={spotaki} layout="fill" objectFit="cover" alt="Spotaki"/>
                </div>
              </figure>
              <div className="card-body">
                <h2 className="card-title">Spotaki</h2>
                <p>A clone of Spotify written by me.</p>
                <ul>Function:
                  <li>Listen to music from Shazam.</li>
                  <li>Look for songs, artists details.</li>
                  <li>Look for playlist.</li>
                  <li>Around you.</li>
                  <li>Get top songs by genres.</li>
                </ul>
                <div className="card-actions justify-end">
                <div className="badge badge-primary">Reactjs</div>
                <div className="badge badge-primary">Redux</div>
                <div className="badge badge-primary">Rapid API</div>
                </div>
              </div>
          </div>
        </section>
      </main>
    </div>
  );
}
