import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";

import Image from "next/image";
import model from "../public/model.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Thong Hoang Danh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">thong</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Thong Hoang
            </h2>
            <h3 className="text-2xl py-2">
              Software Engineering student from Tampere.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Second-year software engineering student from Tampere University
              of Applied Sciences. I am currently focusing on FullStack
              Development. Love chatting about tech. Join me down below and
              let's get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            <div className="relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden">
              <Image src={model} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section className="">
          <div>
            <h3 className="text-3xl py-1">My projects</h3>
          </div>
        </section>
      </main>
    </div>
  );
}
